In [13]:
import pandas as pd

df = pd.read_json("../data/threads_per_group.jsonl", lines=True, orient="records")
df["num_threads"] = df.thread_data.apply(len)
df["news_group"] = df.mbox_file.apply(lambda x: x[:-5])
del df["mbox_file"]
df

,thread_data,num_threads,news_group
0,[{'thread_subject': 'S:Koselig sommer/vinterhu...,2101,no.marked.bolig
1,[{'thread_subject': 'Tandberg TDV 2200 - serie...,1184,no.it.nostalgi
2,[{'thread_subject': 'Engelsk oversettelse av '...,1210,no.skole.diverse
3,"[{'thread_subject': '""Demokrati"" for alle?', ...",636,no.stortinget
4,[{'thread_subject': '* NY WEB-SHOP HOS APPLAUS...,179,no.vr
...,...,...,...
326,"[{'thread_subject': 'Blogging, overtar dette f...",514,no.samfunn.diverse
327,[{'thread_subject': 'Fra World Portal 4U to U ...,887,no.alt.hjemmesider.frontpage
328,[{'thread_subject': 'Begynnelsen p� slutten av...,1833,no.it.telekom.diverse
329,[{'thread_subject': 'Kj�recomputer/forbruksm�l...,7458,no.marked.bil
330,"[{'thread_subject': 'Hvor mye koster Unix?', '...",1931,no.unix

# Top 20 newsgroups 
The 20 news groups with the most threads

In [14]:
df.sort_values("num_threads", ascending=False).head(20)

,thread_data,num_threads,news_group
280,"[{'thread_subject': 'test2', 'num_messages': 1...",54228,no.test
111,[{'thread_subject': 'S: Suuuuper PC - 300mmx (...,52795,no.marked.data
198,"[{'thread_subject': 'FS. CDs', 'num_messages':...",36242,no.marked
220,[{'thread_subject': 'Sikkerhetsfeil i Lion 10....,26200,no.it.os.mac.diverse
144,[{'thread_subject': 'Eldre Datamaskiner - og a...,24904,no.annonser.it.maskinvare.diverse
322,[{'thread_subject': '12 år senere var det tris...,23958,no.alt.frustrasjoner
80,"[{'thread_subject': 'Virus ????????', 'num_mes...",23503,no.pc
318,[{'thread_subject': 'Humble Bundle 3 - flere b...,21261,no.it.os.unix.linux.diverse
166,[{'thread_subject': 'Ø: medreisende på billett...,21235,no.annonser.diverse
123,[{'thread_subject': 'Giveaway of the day for M...,20822,no.it.maskinvare.diverse
65,[{'thread_subject': 'Windows 7 - Admin-problem...,19745,no.it.os.ms-windows.diverse
224,"[{'thread_subject': 'ABBs mor er død', 'num_me...",18402,no.samfunn.politikk.diverse
16,[{'thread_subject': 'Norsk fotballfiasko i VM:...,17950,no.sport.fotball
244,"[{'thread_subject': 'Det ble julegave', 'num_m...",16887,no.alt.gledesutbrudd
31,[{'thread_subject': 'Veterans Day is one month...,16184,no.general
46,[{'thread_subject': 'Grunn til ha android i bi...,14939,no.teknologi.bil
212,"[{'thread_subject': 'K: Knipetak kjøpes', 'num...",13899,no.annonser.bil
292,[{'thread_subject': 'Q:Er det noen som har et ...,13494,no.annonser.it.diverse
236,[{'thread_subject': 'Internett via vassledinga...,13064,no.linux
308,[{'thread_subject': 'Nakkestøtter med innebygd...,12822,no.annonser.audio-video

# Top 20 longest threads

In [15]:
threads_df = pd.DataFrame(
    [
        {"news_group": tup.news_group, **thread_data}
        for tup in df.itertuples()
        for thread_data in tup.thread_data
    ]
).sort_values("num_messages", ascending=False)
threads_df.head(20)

,news_group,thread_subject,num_messages
735669,no.it.tjenester.www.design,Bra Nett: Skrekkeksempel p� d�rlig nettside,2580
508560,no.it.tjenester.www.diverse,Bra Nett: Skrekkeksempel p� d�rlig nettside,2478
401804,no.alt.hjemmesider,Bra Nett: Skrekkeksempel p� d�rlig nettside,2373
1038280,no.amiga,Amiga er back in business ???,2001
531220,no.samfunn.religion,Har troende mennesker lavere IQ?,1904
534849,no.samfunn.religion,Re: �Befrielsen fra korset�,1687
581152,no.fag.psykologi.generell,Sm�djevler.,1459
531868,no.samfunn.religion,Ateistisk darwinisme i fuld blomstring,1303
937202,no.alt.diskusjoner,Har troende mennesker lavere IQ?,1186
531872,no.samfunn.religion,Dette er et under.,1175
434712,no.fag.diverse,Har troende mennesker lavere IQ?,1168
167702,no.alt.undring,Har troende mennesker lavere IQ?,1157
1037472,no.amiga,Re: Antall farger i �yet (Re: Spekulasjon rund...,1144
792394,no.samfunn.politikk.diverse,Dyr har f�lelser og (en viss) intelligens,1131
1039315,no.amiga,IBM-kompatibel vs Amiga,1118
1058168,no.alt.motorsykler,Effekt forskjell mellom v-motorer og rekkefir...,1094
534025,no.samfunn.religion,Religionen evig uten bevis,1093
535274,no.samfunn.religion,Ateisme og agnostisisme,1084
928975,no.fag.filosofi,Kritikk av Alfa 5's sosialisme-tekst,1083
785778,no.samfunn.politikk.diverse,Hva skjedde 11. september?,1075

# Threads across newsgroups

In [23]:
for subject, df_ in threads_df.head(200).groupby("thread_subject"):
    print(
        f"{subject}\n\tNews groups: {df_.news_group.to_list()}\n\tNum messages: {df_.num_messages.sum()}\n"
    )

"Det nytter ikke � bygge seg ut av rushproblematikken"???
	News groups: ['no.teknologi.bil', 'no.samfunn.trafikk', 'no.samfunn.politikk.diverse']
	Num messages: 2258

"Gud" er bare en naturkraft
	News groups: ['no.religion']
	Num messages: 755

"Vandrer mod Lyset!"
	News groups: ['no.samfunn.religion']
	Num messages: 512

%%% Staten er en tyv %%%
	News groups: ['no.samfunn.politikk.diverse']
	Num messages: 505

0,00078% !!!
	News groups: ['no.teknologi.bil', 'no.samfunn.politikk.diverse']
	Num messages: 1063

Allah + Jehova = Gud
	News groups: ['no.samfunn.politikk.diverse']
	Num messages: 455

Amerikansk nasjonal psykose forverres
	News groups: ['no.samfunn.religion', 'no.samfunn.politikk.diverse', 'no.alt.diskusjoner.usa']
	Num messages: 2030

Amiga Next Generation og Playstation 2
	News groups: ['no.amiga']
	Num messages: 479

Amiga er back in business ???
	News groups: ['no.amiga']
	Num messages: 2001

Are the Natural Jews Today God's Chosen People?
	News groups: ['no.religion']
	Num messages: 590

Artikkelen i CW
	News groups: ['no.general']
	Num messages: 441

At vi finner oss i det.
	News groups: ['no.alt.diskusjoner', 'no.general']
	Num messages: 1221

Ateisme og agnostisisme
	News groups: ['no.samfunn.religion']
	Num messages: 1084

Ateismens logiske brister
	News groups: ['no.samfunn.religion', 'no.samfunn.politikk.diverse']
	Num messages: 1128

Ateistisk darwinisme i fuld blomstring
	News groups: ['no.samfunn.religion']
	Num messages: 1303

Aura - healing
	News groups: ['no.fag.diverse', 'no.fag.psykologi.generell', 'no.fag.medisin.diverse']
	Num messages: 1511

Auto-sensur i no.jus og muligens andre gruppper.
	News groups: ['no.general']
	Num messages: 544

Billig forsikring
	News groups: ['no.alt.motorsykler']
	Num messages: 483

Blitz kan drite og dra!!!
	News groups: ['no.general']
	Num messages: 692

Bokb�l
	News groups: ['no.alt.frustrasjoner', 'no.samfunn.politikk.diverse', 'no.samfunn.religion', 'no.kultur.litteratur.diverse', 'no.samfunn.media.radio-tv']
	Num messages: 2522

Bra Nett: Skrekkeksempel p� d�rlig nettside
	News groups: ['no.it.tjenester.www.design', 'no.it.tjenester.www.diverse', 'no.alt.hjemmesider']
	Num messages: 7431

DEFINISJON AV TRO
	News groups: ['no.religion']
	Num messages: 738

Da ble det Honda CBR 600 F4
	News groups: ['no.alt.motorsykler']
	Num messages: 441

Databransjen advarer mot DAB-radioer
	News groups: ['no.samfunn.media.radio-tv', 'no.samfunn.forbruker', 'no.teknologi.audio']
	Num messages: 1764

Det skjedde i de dager...
	News groups: ['no.alt.motorsykler']
	Num messages: 518

Dette er et under.
	News groups: ['no.samfunn.religion']
	Num messages: 1175

Drapstrusler fra Erik Naggum
	News groups: ['no.fag.psykologi.generell', 'no.nettvett']
	Num messages: 1029

Du tror du er trygg?
	News groups: ['no.alt.motorsykler']
	Num messages: 616

Dyr har f�lelser og (en viss) intelligens
	News groups: ['no.samfunn.politikk.diverse', 'no.alt.diskusjoner', 'no.samfunn.naturvern', 'no.fag.landbruk']
	Num messages: 3364

Dyrets ambulansetjeneste-del II.
	News groups: ['no.alt.diskusjoner', 'no.fag.medisin.diverse']
	Num messages: 864

Effekt forskjell  mellom v-motorer og rekkefirere, boksere ?
	News groups: ['no.alt.motorsykler']
	Num messages: 1094

Ehem...
	News groups: ['no.alt.motorsykler']
	Num messages: 655

En sosiolog koser seg
	News groups: ['no.kultur.folklore.ufo']
	Num messages: 436

En tanke i universet?
	News groups: ['no.fag.filosofi']
	Num messages: 421

Er ateister smartere enn religi�se personer?
	News groups: ['no.samfunn.religion', 'no.samfunn.politikk.diverse']
	Num messages: 1037

Er det bedre å tro på en ikke-eksisterende gud enn å ikke tro på noen gud?
	News groups: ['no.samfunn.religion']
	Num messages: 644

Er dette et bra kj�p?
	News groups: ['no.alt.motorsykler']
	Num messages: 444

Er du et godt menneske?
	News groups: ['no.samfunn.religion']
	Num messages: 442

Et tapt evangelium?
	News groups: ['no.samfunn.religion']
	Num messages: 438

Fakta om norsk bistand til "Palestina":
	News groups: ['no.samfunn.politikk.diverse', 'no.general', 'no.samfunn.religion']
	Num messages: 1600

Fakta rundt "mere avgifter for � bygge vei" retorikken
	News groups: ['no.samfunn.politikk.diverse']
	Num messages: 415

Fjernlys om dagen
	News groups: ['no.alt.motorsykler']
	Num messages: 598

Guds rike.
	News groups: ['no.samfunn.religion']
	Num messages: 439

HVA ER V�RST??
	News groups: ['no.bil']
	Num messages: 521

Hannemyr og Henriksen-charteret hans
	News groups: ['no.usenet.admin']
	Num messages: 446

Har troende mennesker lavere IQ?
	News groups: ['no.samfunn.religion', 'no.alt.diskusjoner', 'no.fag.diverse', 'no.alt.undring']
	Num messages: 5415

Hehehey!
	News groups: ['no.alt.motorsykler']
	Num messages: 542

Heisenberg (was: Re: Meningen med livet  (Re: Hjemmeside))
	News groups: ['no.fag.filosofi', 'no.fag.diverse']
	Num messages: 1057

Hent pedofilen hjem!
	News groups: ['no.general']
	Num messages: 442

Homofile par som oppdrar barn?
	News groups: ['no.religion']
	Num messages: 441

Homofili er ingen sinnstilstand  (Re: De homofiles ansvar!)
	News groups: ['no.prat.seksualitet']
	Num messages: 416

Hva definerer en "Amiga"?
	News groups: ['no.amiga']
	Num messages: 765

Hva er lykke? (var Re: evighet)
	News groups: ['no.samfunn.religion']
	Num messages: 475

Hva skjedde 11. september?
	News groups: ['no.samfunn.politikk.diverse', 'no.alt.diskusjoner.usa']
	Num messages: 2133

Hva snakker Johannes om her?
	News groups: ['no.samfunn.religion']
	Num messages: 776

Hvem er hvem p� no.musikk
	News groups: ['no.musikk']
	Num messages: 518

Hvor fort har _du_ kj�rt?
	News groups: ['no.bil']
	Num messages: 497

IBM-kompatibel vs Amiga
	News groups: ['no.amiga', 'no.pc']
	Num messages: 1686

ID
	News groups: ['no.samfunn.religion']
	Num messages: 812

Integreringa i samfunnet av innvandrere er umulig p� kort sikt og vanskelig p� lang sikt !!!
	News groups: ['no.alt.diskusjoner', 'no.samfunn.politikk.innvandring', 'no.general']
	Num messages: 1408

Irak angrepet
	News groups: ['no.general', 'no.prat.politikk']
	Num messages: 1576

It-Fjotter
	News groups: ['no.alt.frustrasjoner']
	Num messages: 444

Japansk eller Tysk bil?
	News groups: ['no.bil']
	Num messages: 547

Jeg er kreasjonist ...
	News groups: ['no.samfunn.religion']
	Num messages: 426

Jenter :-(
	News groups: ['no.alt.pludring']
	Num messages: 859

Kamp mot rasisme:  Ditt eget initativ er det viktigste.
	News groups: ['no.general', 'no.prat.politikk']
	Num messages: 1096

Katastrofeflommen
	News groups: ['no.samfunn.religion']
	Num messages: 440

Klimaendringene har kosmiske årsaker
	News groups: ['no.samfunn.naturvern', 'no.samfunn.politikk.diverse']
	Num messages: 994

Kopibeskyttelse igjen
	News groups: ['no.kultur.musikk.diverse']
	Num messages: 437

Krf-nei til homofile
	News groups: ['no.samfunn.religion']
	Num messages: 427

Kristenhat i praksis
	News groups: ['no.samfunn.religion']
	Num messages: 544

Kritikk av Alfa 5's sosialisme-tekst
	News groups: ['no.fag.filosofi']
	Num messages: 1083

K�ring av 20 beste norske innspillinger.
	News groups: ['no.musikk']
	Num messages: 493

Langfeldt vs. Apeltun S�le: Kriminalisering av porno
	News groups: ['no.alt.diskusjoner', 'no.prat.seksualitet']
	Num messages: 939

Liste over ting som er gratis/nesten gratis og som er g�y/trivelig/meningsfullt
	News groups: ['no.alt.pludring', 'no.alt.motorsykler']
	Num messages: 967

Lund-rapporten.
	News groups: ['no.general']
	Num messages: 570

Mannen p� m�nen
	News groups: ['no.samfunn.politikk.diverse', 'no.fag.psykologi.generell', 'no.samfunn.religion']
	Num messages: 1495

Masturbasjon, var Re: Homofobi!
	News groups: ['no.samfunn.seksualitet']
	Num messages: 432

Millit�rtjeneste?
	News groups: ['no.alt.frustrasjoner', 'no.general', 'no.samfunn.politikk.vaapen', 'no.alt.flame']
	Num messages: 1761

Nesten en innr�mmelse?
	News groups: ['no.samfunn.politikk.innvandring']
	Num messages: 609

N� f�r du bremse, Naggum
	News groups: ['no.general']
	Num messages: 509

N�r finner vi en partner?
	News groups: ['no.prat.seksualitet']
	Num messages: 459

Om � svare p� sinnsforvirrede innlegg.
	News groups: ['no.alt.diskusjoner']
	Num messages: 435

PSYKOPATENES SEKSUELLE DIKTATUR
	News groups: ['no.prat.seksualitet']
	Num messages: 596

Pedofili - fakta eller myter
	News groups: ['no.prat.politikk', 'no.prat.seksualitet']
	Num messages: 1073

Pollettellingstr�d
	News groups: ['no.alt.pludring']
	Num messages: 754

Prostitusjon generelt / prostitusjon i Finnmark
	News groups: ['no.samfunn.seksualitet']
	Num messages: 741

Rar harddisk-feil
	News groups: ['no.amiga']
	Num messages: 443

Re: 0,00078% !!!
	News groups: ['no.fag.diverse', 'no.fag.kjemi']
	Num messages: 972

Re: Allah + Jehova = Gud
	News groups: ['no.samfunn.religion']
	Num messages: 449

Re: Antall farger i �yet (Re: Spekulasjon rundt Amiga, Inc. sine planer
	News groups: ['no.amiga']
	Num messages: 1144

Re: En tanke i universet?
	News groups: ['no.fag.diverse', 'no.samfunn.religion']
	Num messages: 843

Re: Er det bedre å tro på en ikke-eksisterende gud enn å ikke tro på noen gud?
	News groups: ['no.samfunn.politikk.diverse']
	Num messages: 603

Re: Fakta om Jehovas vitner og blod
	News groups: ['no.religion']
	Num messages: 475

Re: Gud er virkelig en allmektig gud
	News groups: ['no.religion']
	Num messages: 1059

Re: Jødehat og kristendomsfiendtlighet
	News groups: ['no.samfunn.religion', 'no.samfunn.politikk.diverse']
	Num messages: 842

Re: Katteproblematikk (Eller Hel*&%#s m�kkakatt)
	News groups: ['no.alt.motorsykler']
	Num messages: 447

Re: Modern Talking
	News groups: ['no.musikk']
	Num messages: 434

Re: N�r finner vi en partner?
	News groups: ['no.alt.diskusjoner']
	Num messages: 588

Re: Pedofili - fakta eller myter
	News groups: ['no.samfunn.seksualitet']
	Num messages: 493

Re: Tr�tt
	News groups: ['no.alt.pludring']
	Num messages: 450

Re: Vedr. Erik Naggum.
	News groups: ['no.nettvett']
	Num messages: 571

Re: �Befrielsen fra korset�
	News groups: ['no.samfunn.religion']
	Num messages: 1687

Religionen evig uten bevis
	News groups: ['no.samfunn.religion']
	Num messages: 1093

Riverdance
	News groups: ['no.kultur.musikk.korps']
	Num messages: 474

Satans helsetilsyn.
	News groups: ['no.alt.diskusjoner']
	Num messages: 833

Se og l�r: �resdrap p� �pen gate !
	News groups: ['no.samfunn.politikk.innvandring', 'no.samfunn.politikk.diverse', 'no.samfunn.religion']
	Num messages: 1368

Selvmordsaksjon i Stockholm
	News groups: ['no.samfunn.politikk.diverse', 'no.samfunn.politikk.innvandring']
	Num messages: 896

Send muslimene hjem !
	News groups: ['no.samfunn.politikk.diverse', 'no.samfunn.religion']
	Num messages: 997

Sjekk linken
	News groups: ['no.alt.frustrasjoner']
	Num messages: 504

Skaff meg en jobb! Levek�r blant flyktninger i Oslo
	News groups: ['no.general']
	Num messages: 452

Slobo
	News groups: ['no.alt.frustrasjoner', 'no.samfunn.politikk.vaapen']
	Num messages: 1618

Sm�djevler.
	News groups: ['no.fag.psykologi.generell', 'no.samfunn.religion', 'no.alt.diskusjoner']
	Num messages: 2864

Som � velge Cognac p� Polet...
	News groups: ['no.alt.motorsykler']
	Num messages: 643

Spekulasjon rundt Amiga, Inc. sine planer
	News groups: ['no.amiga']
	Num messages: 449

Spinn om stenging av IRC-server
	News groups: ['no.general', 'no.alt.diskusjoner', 'no.irc']
	Num messages: 1686

Stretch
	News groups: ['no.alt.pludring', 'no.alt.motorsykler']
	Num messages: 1792

St�tt ytringsfriheten i Norge
	News groups: ['no.general']
	Num messages: 433

Teit...
	News groups: ['no.alt.motorsykler']
	Num messages: 569

Tidenens st�rste popsanger.
	News groups: ['no.musikk']
	Num messages: 581

Trikkesnikere
	News groups: ['no.alt.diskusjoner']
	Num messages: 508

Tuffaste musikvideon just nu
	News groups: ['no.kultur.musikk.diverse']
	Num messages: 1059

Utfordring
	News groups: ['no.samfunn.religion']
	Num messages: 667

VALGET KAN VÆRE ULOVLIG
	News groups: ['no.news.diverse']
	Num messages: 693

Var Hitler kristen?
	News groups: ['no.samfunn.religion']
	Num messages: 917

Vitenskapen er ikke til � stole p�
	News groups: ['no.samfunn.religion']
	Num messages: 657

Vrangforestillinger?  (Re: Media og 'j�der')
	News groups: ['no.prat.seksualitet']
	Num messages: 520

V�r nasjonalist - og stolt av det!
	News groups: ['no.samfunn.politikk.innvandring']
	Num messages: 442

V�r nye statsminister
	News groups: ['no.samfunn.religion']
	Num messages: 679

blondiner er dumme
	News groups: ['no.general']
	Num messages: 686

borte...
	News groups: ['no.alt.motorsykler']
	Num messages: 585

evighet
	News groups: ['no.fag.filosofi']
	Num messages: 637

flerreligi�s klasse
	News groups: ['no.samfunn.religion']
	Num messages: 438

no.alt.marked.sex
	News groups: ['no.samfunn.seksualitet', 'no.alt.config', 'no.alt.frustrasjoner']
	Num messages: 1457

oppfordring:
	News groups: ['no.bil']
	Num messages: 646

repost Sitater av Hitler #1
	News groups: ['no.samfunn.religion']
	Num messages: 434

ta narkosvina
	News groups: ['no.samfunn.narkotika']
	Num messages: 436

�Befrielsen fra korset�
	News groups: ['no.samfunn.politikk.diverse']
	Num messages: 588

�ndelig intelligens (SQ = Spiritual intelligence)
	News groups: ['no.samfunn.religion', 'no.fag.psykologi.generell', 'no.fag.filosofi']
	Num messages: 2022